version: '3'

services:
  web:
    image: leebrandt/kcdc-api
    container_name: node_api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect=0.0.0.0:9229 ./bin/www